name: Deploy API to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.PATH_PROJECT }}

            git pull origin

            docker build -t app-docker:latest .

            docker compose -f docker-compose.prod.yml up -d --build --remove-orphan

            docker compose -f docker-compose-prod.yml exec app-docker php artisan migrate --force

            docker image prune -af
            docker container prune -f

            echo "==> Deployment completed successfully!"
